export const questions = {
  financialGuidance: [
    { id: 1, text: "What is your current level of financial literacy?", type: 'dropdown', options: ['Beginner', 'Intermediate', 'Advanced'] },
    { id: 2, text: "What are your primary financial goals?", type: 'dropdown', options: ['Saving for retirement', 'Buying a home', 'Starting a business', 'Paying off debt', 'Building an emergency fund'] },
    { id: 3, text: "How much can you save monthly?", type: 'dropdown', options: ['< $100', '$100 - $500', '$500 - $1000', '> $1000'] },
    { id: 4, text: "What type of financial advice are you seeking?", type: 'dropdown', options: ['Budgeting', 'Saving', 'Investing', 'Debt Management'] },
    { id: 5, text: "Do you have any existing investments?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 6, text: "How often do you review your financial plan?", type: 'dropdown', options: ['Never', 'Once a year', 'Every 6 months', 'Every month'] },
    { id: 7, text: "What is your risk tolerance?", type: 'dropdown', options: ['Low', 'Medium', 'High'] },
    { id: 8, text: "Do you use any financial management tools?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 9, text: "How confident are you in managing your finances?", type: 'dropdown', options: ['Not confident', 'Somewhat confident', 'Confident', 'Very confident'] },
    { id: 10, text: "What is your preferred method of receiving financial advice?", type: 'dropdown', options: ['Online resources', 'Financial advisor', 'Workshops', 'Books'] },
  ],
  creditScoreTips: [
    { id: 1, text: "What is your current credit score range?", type: 'dropdown', options: ['< 500', '500-600', '600-700', '> 700'] },
    { id: 2, text: "Do you have any outstanding debts?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 3, text: "Are you currently using a credit card?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 4, text: "What is your primary financial goal?", type: 'dropdown', options: ['Improve Credit Score', 'Maintain Good Credit Score'] },
    { id: 5, text: "Have you ever defaulted on a loan?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 6, text: "How many credit cards do you have?", type: 'dropdown', options: ['None', '1-2', '3-4', '5 or more'] },
    { id: 7, text: "Do you regularly check your credit report?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 8, text: "Have you ever declared bankruptcy?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 9, text: "What is your credit utilization ratio?", type: 'dropdown', options: ['< 30%', '30-50%', '50-70%', '> 70%'] },
    { id: 10, text: "Do you know your credit score?", type: 'dropdown', options: ['Yes', 'No'] },
  ],
  savingsPlans: [
    { id: 1, text: "How much can you save monthly?", type: 'dropdown', options: ['< $100', '$100 - $500', '$500 - $1000', '> $1000'] },
    { id: 2, text: "Do you have a savings goal?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 3, text: "How long do you plan to save?", type: 'dropdown', options: ['< 1 year', '1-3 years', '3-5 years', '> 5 years'] },
    { id: 4, text: "Are you saving for a specific purpose?", type: 'dropdown', options: ['Emergency Fund', 'Retirement', 'Education', 'Vacation', 'Other (please specify)'] },
    { id: 5, text: "Do you have an existing savings account?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 6, text: "How often do you deposit into your savings account?", type: 'dropdown', options: ['Weekly', 'Monthly', 'Quarterly', 'Annually'] },
    { id: 7, text: "What type of savings account do you have?", type: 'dropdown', options: ['Regular Savings', 'High-Yield Savings', 'Money Market', 'Certificate of Deposit (CD)'] },
    { id: 8, text: "Do you have an emergency fund?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 9, text: "How much do you have saved in your emergency fund?", type: 'dropdown', options: ['< $500', '$500 - $1000', '$1000 - $5000', '> $5000'] },
    { id: 10, text: "How confident are you in your current savings plan?", type: 'dropdown', options: ['Not confident', 'Somewhat confident', 'Confident', 'Very confident'] },
  ],
  loanOptions: [
    { id: 1, text: "What type of loan are you looking for?", type: 'dropdown', options: ['Personal Loan', 'Home Loan', 'Auto Loan', 'Education Loan'] },
    { id: 2, text: "What is the amount you need?", type: 'dropdown', options: ['< $5,000', '$5,000 - $10,000', '$10,000 - $20,000', '> $20,000'] },
    { id: 3, text: "What is your credit score range?", type: 'dropdown', options: ['< 500', '500-600', '600-700', '> 700'] },
    { id: 4, text: "Do you have any existing loans?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 5, text: "What is your annual income?", type: 'dropdown', options: ['< $20,000', '$20,000 - $50,000', '$50,000 - $100,000', '> $100,000'] },
    { id: 6, text: "How do you plan to use the loan?", type: 'dropdown', options: ['Debt Consolidation', 'Home Improvement', 'Major Purchase', 'Education', 'Other'] },
    { id: 7, text: "What is the desired loan term?", type: 'dropdown', options: ['< 1 year', '1-3 years', '3-5 years', '> 5 years'] },
    { id: 8, text: "Have you ever defaulted on a loan?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 9, text: "Do you have a co-signer?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 10, text: "How quickly do you need the loan?", type: 'dropdown', options: ['Immediately', 'Within 1 month', 'Within 3 months', 'No rush'] },
  ],
  investmentIdeas: [
    { id: 1, text: "What is your investment experience?", type: 'dropdown', options: ['Beginner', 'Intermediate', 'Advanced'] },
    { id: 2, text: "What type of investments are you interested in?", type: 'dropdown', options: ['Stocks', 'Bonds', 'Real Estate', 'Mutual Funds', 'Cryptocurrency', 'Other'] },
    { id: 3, text: "What is your investment horizon?", type: 'dropdown', options: ['< 1 year', '1-3 years', '3-5 years', '> 5 years'] },
    { id: 4, text: "What is your risk tolerance?", type: 'dropdown', options: ['Low', 'Medium', 'High'] },
    { id: 5, text: "What is your investment goal?", type: 'dropdown', options: ['Growth', 'Income', 'Preservation of capital', 'Speculation'] },
    { id: 6, text: "How much can you invest initially?", type: 'dropdown', options: ['< $1,000', '$1,000 - $5,000', '$5,000 - $10,000', '> $10,000'] },
    { id: 7, text: "How much can you invest monthly?", type: 'dropdown', options: ['< $100', '$100 - $500', '$500 - $1,000', '> $1,000'] },
    { id: 8, text: "Do you have a diversified portfolio?", type: 'dropdown', options: ['Yes', 'No'] },
    { id: 9, text: "How often do you review your investments?", type: 'dropdown', options: ['Never', 'Once a year', 'Every 6 months', 'Every month'] },
    { id: 10, text: "What type of investment advice are you seeking?", type: 'dropdown', options: ['Self-directed', 'Financial advisor', 'Robo-advisor', 'None'] },
  ],
};
